server:
  port: 8080
  servlet:
    context-path:

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3307/identity_service3}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    password: ${DBMS_PASSWORD:28082001}
    username: ${DBMS_USERNAME:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#  M9ebpI+8t3asjzq0M/hMUmWFLLFfp/RjTqB5DLc2EXSm01nVDWnHCAtKozeFMQC4
#  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
jwt:
  signerKey: "M9ebpI+8t3asjzq0M/hMUmWFLLFfp/RjTqB5DLc2EXSm01nVDWnHCAtKozeFMQC4"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds
